//! ROI calculator for LLM deployments.
//!
//! Provides [`RoiCalculator`] to compute return-on-investment metrics,
//! break-even analysis, deployment comparison, and sensitivity analysis
//! for LLM deployments described by [`LlmDeployment`].

// ---------------------------------------------------------------------------
// ValueStream
// ---------------------------------------------------------------------------

/// A single source of business value generated by an LLM deployment.
#[derive(Debug, Clone)]
pub enum ValueStream {
    /// Direct cost saving (e.g. replacing a SaaS tool).
    CostSaving {
        /// Monthly saving in USD.
        usd_per_month: f64,
    },
    /// New revenue enabled by the LLM capability.
    RevenueGenerated {
        /// Monthly revenue in USD.
        usd_per_month: f64,
    },
    /// Productivity gain from time saved.
    TimeSaved {
        /// Hours saved per month.
        hours_per_month: f64,
        /// Fully-loaded hourly cost of the staff time saved.
        hourly_rate_usd: f64,
    },
    /// Reduction in costly errors or incidents.
    ErrorReduction {
        /// Number of incidents prevented per month.
        incidents_prevented: f64,
        /// Average cost per incident in USD.
        cost_per_incident: f64,
    },
}

impl ValueStream {
    /// Monthly value in USD contributed by this stream.
    pub fn monthly_value(&self) -> f64 {
        match self {
            ValueStream::CostSaving { usd_per_month } => *usd_per_month,
            ValueStream::RevenueGenerated { usd_per_month } => *usd_per_month,
            ValueStream::TimeSaved {
                hours_per_month,
                hourly_rate_usd,
            } => hours_per_month * hourly_rate_usd,
            ValueStream::ErrorReduction {
                incidents_prevented,
                cost_per_incident,
            } => incidents_prevented * cost_per_incident,
        }
    }
}

// ---------------------------------------------------------------------------
// LlmDeployment
// ---------------------------------------------------------------------------

/// Descriptor of a live LLM deployment for ROI analysis.
#[derive(Debug, Clone)]
pub struct LlmDeployment {
    /// Human-readable deployment name.
    pub name: String,
    /// Recurring monthly operating cost in USD (inference, hosting, etc.).
    pub monthly_cost_usd: f64,
    /// All value streams this deployment produces.
    pub value_streams: Vec<ValueStream>,
    /// One-time upfront deployment / integration cost in USD.
    pub deployment_cost_usd: f64,
    /// Number of months the deployment has been running.
    pub months_running: u32,
}

// ---------------------------------------------------------------------------
// RoiMetrics
// ---------------------------------------------------------------------------

/// Computed ROI metrics for a deployment.
#[derive(Debug, Clone, PartialEq)]
pub struct RoiMetrics {
    /// Total capital invested to date (deployment cost + running costs).
    pub total_invested_usd: f64,
    /// Total value generated to date across all value streams.
    pub total_value_usd: f64,
    /// Net benefit: `total_value_usd - total_invested_usd`.
    pub net_benefit_usd: f64,
    /// ROI as a percentage: `(net_benefit / total_invested) * 100`.
    ///
    /// Returns `0.0` when `total_invested_usd == 0`.
    pub roi_pct: f64,
    /// Months until cumulative value equals cumulative cost (break-even).
    ///
    /// `f64::INFINITY` when value per month is zero or negative.
    pub payback_months: f64,
    /// Average net value generated per month (value/month - cost/month).
    pub monthly_roi: f64,
}

// ---------------------------------------------------------------------------
// RoiCalculator
// ---------------------------------------------------------------------------

/// Stateless ROI computation engine for LLM deployments.
///
/// # Example
/// ```
/// use llm_cost_dashboard::roi_calculator::{
///     LlmDeployment, RoiCalculator, ValueStream,
/// };
///
/// let deployment = LlmDeployment {
///     name: "Support Bot".to_string(),
///     monthly_cost_usd: 500.0,
///     value_streams: vec![ValueStream::CostSaving { usd_per_month: 2000.0 }],
///     deployment_cost_usd: 5000.0,
///     months_running: 6,
/// };
/// let metrics = RoiCalculator::compute(&deployment);
/// assert!(metrics.roi_pct > 0.0);
/// ```
pub struct RoiCalculator;

impl RoiCalculator {
    /// Compute ROI metrics for a single deployment.
    pub fn compute(deployment: &LlmDeployment) -> RoiMetrics {
        let months = deployment.months_running as f64;
        let total_invested =
            deployment.deployment_cost_usd + deployment.monthly_cost_usd * months;
        let monthly_value: f64 = deployment
            .value_streams
            .iter()
            .map(|v| v.monthly_value())
            .sum();
        let total_value = monthly_value * months;
        let net_benefit = total_value - total_invested;

        let roi_pct = if total_invested == 0.0 {
            0.0
        } else {
            (net_benefit / total_invested) * 100.0
        };

        let monthly_net = monthly_value - deployment.monthly_cost_usd;
        let monthly_roi = monthly_net;

        // Payback: deployment_cost / monthly_net_value (when positive).
        let payback_months = if monthly_net <= 0.0 {
            f64::INFINITY
        } else {
            deployment.deployment_cost_usd / monthly_net
        };

        RoiMetrics {
            total_invested_usd: total_invested,
            total_value_usd: total_value,
            net_benefit_usd: net_benefit,
            roi_pct,
            payback_months,
            monthly_roi,
        }
    }

    /// Determine the first month at which cumulative value exceeds cumulative
    /// cost. Returns `None` if the deployment never breaks even within 1 200
    /// months (100 years) or if the monthly value is non-positive.
    pub fn breakeven_month(deployment: &LlmDeployment) -> Option<u32> {
        let monthly_value: f64 = deployment
            .value_streams
            .iter()
            .map(|v| v.monthly_value())
            .sum();

        if monthly_value <= 0.0 {
            return None;
        }

        for month in 1u32..=1_200 {
            let cumulative_cost =
                deployment.deployment_cost_usd + deployment.monthly_cost_usd * month as f64;
            let cumulative_value = monthly_value * month as f64;
            if cumulative_value >= cumulative_cost {
                return Some(month);
            }
        }
        None
    }

    /// Compute ROI for all deployments and return them sorted by `roi_pct`
    /// descending (best first).
    pub fn compare_deployments(deployments: &[LlmDeployment]) -> Vec<(&LlmDeployment, RoiMetrics)> {
        let mut results: Vec<(&LlmDeployment, RoiMetrics)> = deployments
            .iter()
            .map(|d| (d, Self::compute(d)))
            .collect();
        results.sort_by(|a, b| {
            b.1.roi_pct
                .partial_cmp(&a.1.roi_pct)
                .unwrap_or(std::cmp::Ordering::Equal)
        });
        results
    }

    /// Perform sensitivity analysis by perturbing costs and values by the
    /// given delta percentages.
    ///
    /// - `cost_delta_pct`: percentage change applied to `monthly_cost_usd` and
    ///   `deployment_cost_usd` (e.g. `10.0` = +10%).
    /// - `value_delta_pct`: percentage change applied to every value stream's
    ///   monthly value (e.g. `-20.0` = −20%).
    pub fn sensitivity_analysis(
        deployment: &LlmDeployment,
        cost_delta_pct: f64,
        value_delta_pct: f64,
    ) -> RoiMetrics {
        let cost_factor = 1.0 + cost_delta_pct / 100.0;
        let value_factor = 1.0 + value_delta_pct / 100.0;

        // Build a modified deployment.
        let perturbed_streams: Vec<ValueStream> = deployment
            .value_streams
            .iter()
            .map(|vs| match vs {
                ValueStream::CostSaving { usd_per_month } => ValueStream::CostSaving {
                    usd_per_month: usd_per_month * value_factor,
                },
                ValueStream::RevenueGenerated { usd_per_month } => {
                    ValueStream::RevenueGenerated {
                        usd_per_month: usd_per_month * value_factor,
                    }
                }
                ValueStream::TimeSaved {
                    hours_per_month,
                    hourly_rate_usd,
                } => ValueStream::TimeSaved {
                    hours_per_month: hours_per_month * value_factor,
                    hourly_rate_usd: *hourly_rate_usd,
                },
                ValueStream::ErrorReduction {
                    incidents_prevented,
                    cost_per_incident,
                } => ValueStream::ErrorReduction {
                    incidents_prevented: incidents_prevented * value_factor,
                    cost_per_incident: *cost_per_incident,
                },
            })
            .collect();

        let perturbed = LlmDeployment {
            name: deployment.name.clone(),
            monthly_cost_usd: deployment.monthly_cost_usd * cost_factor,
            value_streams: perturbed_streams,
            deployment_cost_usd: deployment.deployment_cost_usd * cost_factor,
            months_running: deployment.months_running,
        };

        Self::compute(&perturbed)
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    fn support_bot() -> LlmDeployment {
        LlmDeployment {
            name: "Support Bot".to_string(),
            monthly_cost_usd: 500.0,
            value_streams: vec![
                ValueStream::CostSaving { usd_per_month: 2_000.0 },
                ValueStream::TimeSaved {
                    hours_per_month: 40.0,
                    hourly_rate_usd: 50.0,
                },
            ],
            deployment_cost_usd: 5_000.0,
            months_running: 6,
        }
    }

    fn loss_maker() -> LlmDeployment {
        LlmDeployment {
            name: "Loss Maker".to_string(),
            monthly_cost_usd: 3_000.0,
            value_streams: vec![ValueStream::CostSaving { usd_per_month: 500.0 }],
            deployment_cost_usd: 10_000.0,
            months_running: 3,
        }
    }

    #[test]
    fn test_monthly_value_cost_saving() {
        let vs = ValueStream::CostSaving { usd_per_month: 1_000.0 };
        assert!((vs.monthly_value() - 1_000.0).abs() < 1e-6);
    }

    #[test]
    fn test_monthly_value_revenue() {
        let vs = ValueStream::RevenueGenerated { usd_per_month: 500.0 };
        assert!((vs.monthly_value() - 500.0).abs() < 1e-6);
    }

    #[test]
    fn test_monthly_value_time_saved() {
        let vs = ValueStream::TimeSaved {
            hours_per_month: 10.0,
            hourly_rate_usd: 100.0,
        };
        assert!((vs.monthly_value() - 1_000.0).abs() < 1e-6);
    }

    #[test]
    fn test_monthly_value_error_reduction() {
        let vs = ValueStream::ErrorReduction {
            incidents_prevented: 5.0,
            cost_per_incident: 200.0,
        };
        assert!((vs.monthly_value() - 1_000.0).abs() < 1e-6);
    }

    #[test]
    fn test_compute_positive_roi() {
        let d = support_bot();
        let m = RoiCalculator::compute(&d);
        // Monthly value = 2000 + 40*50 = 4000; cost = 500; net = 3500/mo
        // total_invested = 5000 + 500*6 = 8000
        // total_value = 4000*6 = 24000
        assert!((m.total_invested_usd - 8_000.0).abs() < 1e-3);
        assert!((m.total_value_usd - 24_000.0).abs() < 1e-3);
        assert!((m.net_benefit_usd - 16_000.0).abs() < 1e-3);
        assert!(m.roi_pct > 0.0);
        assert!(m.payback_months.is_finite());
    }

    #[test]
    fn test_compute_negative_roi() {
        let d = loss_maker();
        let m = RoiCalculator::compute(&d);
        assert!(m.net_benefit_usd < 0.0);
        assert!(m.roi_pct < 0.0);
        // Monthly net = 500 - 3000 = -2500 → payback infinite.
        assert!(m.payback_months.is_infinite());
    }

    #[test]
    fn test_compute_zero_investment() {
        let d = LlmDeployment {
            name: "Free".to_string(),
            monthly_cost_usd: 0.0,
            value_streams: vec![ValueStream::CostSaving { usd_per_month: 0.0 }],
            deployment_cost_usd: 0.0,
            months_running: 0,
        };
        let m = RoiCalculator::compute(&d);
        assert_eq!(m.roi_pct, 0.0);
    }

    #[test]
    fn test_breakeven_month_positive() {
        let d = support_bot();
        // Monthly net = 4000 - 500 = 3500; deployment_cost = 5000
        // Break-even at month 2 (7000 value > 5000 deployment cost + 1000 running = 6000)
        let be = RoiCalculator::breakeven_month(&d);
        assert!(be.is_some());
        assert!(be.unwrap() >= 1);
    }

    #[test]
    fn test_breakeven_month_never() {
        let d = loss_maker();
        assert!(RoiCalculator::breakeven_month(&d).is_none());
    }

    #[test]
    fn test_breakeven_month_zero_value() {
        let d = LlmDeployment {
            name: "Zero Value".to_string(),
            monthly_cost_usd: 100.0,
            value_streams: vec![],
            deployment_cost_usd: 1_000.0,
            months_running: 1,
        };
        assert!(RoiCalculator::breakeven_month(&d).is_none());
    }

    #[test]
    fn test_compare_deployments_sorted() {
        let deployments = vec![loss_maker(), support_bot()];
        let ranked = RoiCalculator::compare_deployments(&deployments);
        assert_eq!(ranked.len(), 2);
        // Support bot should rank first (higher ROI).
        assert_eq!(ranked[0].0.name, "Support Bot");
        assert_eq!(ranked[1].0.name, "Loss Maker");
    }

    #[test]
    fn test_sensitivity_analysis_cost_increase() {
        let d = support_bot();
        let baseline = RoiCalculator::compute(&d);
        let stressed = RoiCalculator::sensitivity_analysis(&d, 50.0, 0.0);
        // Higher cost → lower ROI.
        assert!(stressed.roi_pct < baseline.roi_pct);
    }

    #[test]
    fn test_sensitivity_analysis_value_decrease() {
        let d = support_bot();
        let baseline = RoiCalculator::compute(&d);
        let stressed = RoiCalculator::sensitivity_analysis(&d, 0.0, -50.0);
        // Lower value → lower ROI.
        assert!(stressed.roi_pct < baseline.roi_pct);
    }

    #[test]
    fn test_sensitivity_analysis_no_change() {
        let d = support_bot();
        let baseline = RoiCalculator::compute(&d);
        let same = RoiCalculator::sensitivity_analysis(&d, 0.0, 0.0);
        assert!((same.roi_pct - baseline.roi_pct).abs() < 1e-6);
    }

    #[test]
    fn test_payback_finite_when_profitable() {
        let d = support_bot();
        let m = RoiCalculator::compute(&d);
        assert!(m.payback_months.is_finite());
        assert!(m.payback_months > 0.0);
    }
}
